django_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls')),
    path('ticket/', include('ticket.urls')),
    path('accounts/', include('users.urls')),
]

ticket/urls.py
from django.urls import path
from . import views
from .views import Ticket_Details, All_Tickets, Ticket_queue, Workspace, All_Closed_Tickets

urlpatterns = [
    path('ticket-details/<int:pk>/', Ticket_Details.as_view(), name='ticket-details'),
    path('create-ticket/', views.create_ticket, name='create-ticket'),
    path('update-ticket/<int:pk>/', views.update_ticket, name='update-ticket'),
    path('all-tickets/', All_Tickets.as_view(), name='all-tickets'),
    path('ticket-queue/', Ticket_queue.as_view(), name='ticket-queue'),
    path('accept-ticket/<int:pk>/', views.accept_ticket, name='accept-ticket'),
    path('close-ticket/<int:pk>/', views.close_ticket, name='close-ticket'),
    path('workspace/', Workspace.as_view(), name='workspace'),
    path('all-closed-tickets/', All_Closed_Tickets.as_view(), name='all-closed-tickets'),
    path('report/', views.report, name='report'),
]

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('register-customer/', views.register_customer, name='register-customer'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
]

ticket/models.py
import uuid
from django.db import models
from users.models import User,Department


class Ticket(models.Model):
    status_choices = (
        ('Active', 'Active'),
        ('Completed', 'Completed'),
        ('Pending', 'Pending'),
    )

    type_choices = (
        ('print', 'Принтер'),
        ('computer', 'Компьютер'),
        ('bars', 'БАРС'),
        ('internet', 'Интернет'),
        ('mounting', 'Установка оборудования'),
    )

    ticket_number = models.UUIDField(default=uuid.uuid4)
    title = models.CharField(max_length=100)
    description = models.TextField()
    created_by = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name='created_by')
    date_created = models.DateTimeField(auto_now_add=True)
    assigned_to = models.ForeignKey(User, on_delete=models.DO_NOTHING, null=True, blank=True)
    is_resolved = models.BooleanField(default=False)
    closed_date = models.DateTimeField(null=True, blank=True)
    ticket_status = models.CharField(max_length=20, choices=status_choices)
    department = models.ForeignKey(Department, on_delete=models.PROTECT, null=True, blank=True)
    ticket_type = models.CharField(max_length=30, choices=type_choices)

    def __str__(self):
        return self.title

ticket/views.py
import datetime
import io

from django.http import HttpResponse
from docxtpl import DocxTemplate

from django.shortcuts import render, redirect
from django.contrib import messages
from django.views.generic import DetailView

from .models import Ticket
from .form import CreateTicketForm, UpdateTicketForm
from django.contrib.auth.decorators import login_required
from django.views.generic.list import ListView


# детали заявки
class Ticket_Details(DetailView):
    model = Ticket
    template_name = 'ticket/ticket_details.html'


class Tickets_Legacy(ListView):
    paginate_by = 5
    model = Ticket
    template_name = 'ticket/all_tickets.html'
    context_object_name = 'tickets'

    def get_queryset(self):
        return Ticket.objects.filter(created_by=self.request.user).order_by('-date_created')


# @login_required
# def ticket_details(request, pk):
#     ticket = Ticket.objects.get(pk=pk)
#     users_tickets = User.objects.get(username=ticket.created_by)
#     tickets_legacy = users_tickets.created_by.all()
#     context = {'ticket': ticket, 'tickets_legacy': tickets_legacy}
#     return render(request, 'ticket/ticket_details.html', context)


"""Для юзеров"""


# Создане заявки
@login_required
def create_ticket(request):
    if request.method == 'POST':
        form = CreateTicketForm(request.POST)
        if form.is_valid():
            ticket = form.save(commit=False)
            ticket.created_by = request.user
            ticket.ticket_status = 'Pending'
            ticket.department = request.user.department
            ticket.save()
            messages.info(request, 'Заявка успешно создана.')
            return redirect('dashboard')
        else:
            messages.warning(request, 'Что-то пошло не так. Проверьте введённые данные.')
            return redirect('create-ticket')
    else:
        form = CreateTicketForm()
        context = {'form': form}
        return render(request, 'ticket/create_ticket.html', context)


# Изменение заявки
@login_required
def update_ticket(request, pk):
    ticket = Ticket.objects.get(pk=pk)
    if not ticket.is_resolved:
        if request.method == 'POST':
            form = UpdateTicketForm(request.POST, instance=ticket)
            if form.is_valid():
                form.save()
                messages.info(request, 'Заявка успешно обнавлена.')
                return redirect('dashboard')
            else:
                messages.warning(request, 'Что-то пошло не так. Проверьте ввeдённые данные.')
        else:
            form = UpdateTicketForm(instance=ticket)
            context = {'form': form}
            return render(request, 'ticket/update_ticket.html', context)
    else:
        messages.warning(request, 'Заявка закрыта. Изменения невозможны.')
        return redirect('dashboard')


# Просмотр всех созданных заявок
class All_Tickets(ListView):
    paginate_by = 5
    model = Ticket
    template_name = 'ticket/all_tickets.html'
    context_object_name = 'tickets'

    def get_queryset(self):
        return Ticket.objects.filter(created_by=self.request.user).order_by('-date_created')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


#
# @login_required
# def all_tickets(request):
#     tickets = Ticket.objects.filter(created_by=request.user).order_by('-date_created')
#     paginator = Paginator(tickets, 10)
#     page_number = request.GET.get('page')
#     page_obj = paginator.get_page(page_number)
#     context = {'tickets': tickets, 'page_obj': page_obj}
#     return render(request, 'ticket/all_tickets.html', context)


"""Для сотрудников"""


# просмотр очетеди заявок
class Ticket_queue(ListView):
    model = Ticket
    paginate_by = 10
    template_name = 'ticket/ticket_queue.html'
    context_object_name = 'tickets'

    def get_queryset(self):
        return Ticket.objects.filter(ticket_status='Pending')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


# @login_required
# def ticket_queue(request):
#     tickets = Ticket.objects.filter(ticket_status='Pending')
#     context = {'tickets': tickets}
#     return render(request, 'ticket/ticket_queue.html', context)


# Принтяие заявки из очереди
@login_required
def accept_ticket(request, pk):
    ticket = Ticket.objects.get(pk=pk)
    ticket.assigned_to = request.user
    ticket.ticket_status = 'Active'
    ticket.save()
    messages.info(request, 'Заявка принята.')
    return redirect('workspace')


# Закрытие заявки
@login_required
def close_ticket(request, pk):
    ticket = Ticket.objects.get(pk=pk)
    ticket.ticket_status = 'Completed'
    ticket.is_resolved = True
    ticket.closed_date = datetime.datetime.now()
    ticket.save()
    messages.info(request, 'Заявка выполнена.')
    return redirect('ticket-queue')


# Заявка в работе
class Workspace(ListView):
    model = Ticket
    paginate_by = 5
    template_name = 'ticket/workspace.html'
    context_object_name = 'tickets'

    def get_queryset(self):
        return Ticket.objects.filter(assigned_to=self.request.user, is_resolved=False)


# @login_required
# def workspace(request):
#     tickets = Ticket.objects.filter(assigned_to=request.user, is_resolved=False)
#     context = {'tickets': tickets}
#     return render(request, 'ticket/workspace.html', context)


# Все закрытые заявки
class All_Closed_Tickets(ListView):
    model = Ticket
    paginate_by = 5
    template_name = 'ticket/all_closed_tickets.html'
    context_object_name = 'tickets'

    def get_queryset(self):
        return Ticket.objects.filter(assigned_to=self.request.user, is_resolved=True)


# @login_required
# def all_closed_tickets(request):
#     tickets = Ticket.objects.filter(assigned_to=request.user, is_resolved=True)
#     context = {'tickets': tickets}
#     return render(request, 'ticket/all_closed_tickets.html', context)

# @login_required
# def report(request):
#     return render(request, 'ticket/report.html')


class Report(ListView):
    model = Ticket
    template_name = 'ticket/report.html'
    context_object_name = 'tickets'

    def get_queryset(self):
        return Ticket.objects.filter(assigned_to=self.request.user, is_resolved=True)

    def get_report(self):
        doc = DocxTemplate("static/ticket/docx/report-sample.docx")
        context = {'last_name': self.request.user.last_name,
                   'first_name': self.request.user.first_name}
        doc.render(context)

        buffer = io.BytesIO()
        doc.save(buffer)
        buffer.seek(0)
        return doc


def report(request):
    now = datetime.datetime.now()
    tickets = Ticket.objects.filter(assigned_to=request.user, is_resolved=True, closed_date__month=now.month)
    print_len = 0
    comp_len = 0
    bars_len = 0
    internet_len = 0
    mount_len = 0
    for ticket in tickets:
        if ticket.ticket_type == 'print':
            print_len += 1
        elif ticket.ticket_type == 'computer':
            comp_len += 1
        elif ticket.ticket_type == 'bars':
            bars_len += 1
        elif ticket.ticket_type == 'internet':
            internet_len += 1
        elif ticket.ticket_type == 'mounting':
            mount_len += 1
        else:
            pass

    doc = DocxTemplate("ticket/static/ticket/docx/report-sample.docx")
    rest = {'last_name': request.user.last_name,
            'first_name': request.user.first_name,
            'date': now.date(),
            'month': '{0:%B}'.format(now),
            'number': len(tickets),
            'print': print_len,
            'computer': comp_len,
            'bars': bars_len,
            'internet': internet_len,
            'mounting': mount_len,
            }
    doc.render(rest)
    buffer = io.BytesIO()
    doc.save(buffer)
    buffer.seek(0)

    response = HttpResponse(
        buffer.getvalue(),
        content_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    )

    response["Content-Disposition"] = f'attachment; filename = "{now.date()}-reporte.docx"'
    response["Content-Encoding"] = "UTF-8"
    return response

templates/ticket/all_closed_tickets.html
{% extends 'base.html' %}

{% block content %}
<div class="card mx-auto" style="width: 76rem;">
    <div class="card-body">
        <h5 class="card-title mb-3">Закрытые заявки</h5>

        <table class="table table-bordered" id="sortedTable">
            <thead>
                <th scope="col" onclick="sortTable(0)">Отделение</th>
                <th scope="col" onclick="sortTable(0)">Тип</th>
                <th scope="col" onclick="sortTable(1)">Название</th>
                <th scope="col" onclick="sortTable(2)">Дата создания</th>
                <th scope="col" onclick="sortTable(3)">Кем создана</th>
                <th scope="col">Статус</th>
                <th scope="col">Действия</th>
            </thead>
            <tbody>
            {% for ticket in tickets %}
                <tr>
                    <td><small>{{ticket.department}}</small></td>
                    <td><small>{{ticket.get_ticket_type_display}}</small></td>
                    <td><small>{{ticket.title}}</small></td>
                    <td><small>{{ticket.date_created}}</small></td>
                    <td><small>{{ticket.created_by.last_name}} {{ticket.created_by.first_name}}</small></td>
                    {% if ticket.ticket_status == 'Active' %}
                    <td><span class="badge bg-success">Активна</span></td>
                    {% elif ticket.ticket_status == 'Pending' %}
                    <td><span class="badge bg-warning">Ожидание</span></td>
                    {% elif ticket.ticket_status == 'Completed' %}
                    <td><span class="badge bg-danger">Закрыта</span></td>
                    {% endif %}
                    <td><small><a href="{% url 'ticket-details' ticket.pk %}">Детали</a> </small></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock content %}

templates/ticket/all_tickets.html
{% extends 'base.html' %}

{% block content %}
<div class="card mx-auto" style="width: 76rem;">
    <div class="card-body">
        <h5 class="card-title mb-3">Очередь заявок</h5>

        <table class="table table-bordered" id="sortedTable">
            <thead>
                <th scope="col" onclick="sortTable(0)">Отделение</th>
                <th scope="col" onclick="sortTable(0)">Тип</th>
                <th scope="col" onclick="sortTable(1)">Название</th>
                <th scope="col" onclick="sortTable(2)">Дата создания</th>
                <th scope="col" onclick="sortTable(3)">Кем принята</th>
                <th scope="col">Статус</th>
                <th scope="col">Действия</th>
            </thead>
            <tbody>
            {% for ticket in tickets %}
                <tr>
                    <td><small>{{ticket.department}}</small></td>
                    <td><small>{{ticket.get_ticket_type_display}}</small></td>
                    <td><small>{{ticket.title}}</small></td>
                    <td><small>{{ticket.date_created}}</small></td>
                    {% if ticket.assigned_to %}
                    <td><small>{{ticket.assigned_to.last_name}} {{ticket.assigned_to.first_name}}</small></td>
                    {% else %}
                    <td><small>------</small></td>
                    {% endif %}
                    {% if ticket.ticket_status == 'Active' %}
                    <td><span class="badge bg-success">Активна</span></td>
                    {% elif ticket.ticket_status == 'Pending' %}
                    <td><span class="badge bg-warning">Ожидание</span></td>
                    {% elif ticket.ticket_status == 'Completed' %}
                    <td><span class="badge bg-danger">Закрыта</span></td>
                    {% endif %}
                    <td><small><a href="{% url 'ticket-details' ticket.pk %}">Детали</a> </small></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock content %}

templates/ticket/create_ticket.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block content %}

<div class="row">
    <div class="col-md-6">
        <div class="card mx-auto" style="width: 40em;">
            <div class="card-body">
                <h5 class="card-title mb-3">Новая заявка</h5>

                <form method="POST">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label class="form-label">Название</label>
                        {% render_field form.title class="form-control" %}
                    </div>
                    <div class="mb-3">
                        <label class="form-label">С чем проблема?</label>
                        {% render_field form.ticket_type class="form-control" %}
                    </div>

                    <div class="mb-3">
                        <label class="form-label">Текст заявки</label>
                        {% render_field form.description class="form-control" %}
                    </div>

                    <button class="btn btn-primary">Подтвердить</button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/ticket/report.html
{% extends 'base.html' %}

{% block content %}
<section class="container mt-5">
    <div class="p-5 mb-4 bg-light rounded-3">
        <div class="container-fluid py5">
            <h1 class="display-5 fw-bold">Тут будут отчёты</h1>
        </div>
    </div>
</section>
{% endblock content %}

templates/ticket/ticket_details.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <div class="col-md-6">
        <div class="card mx-auto" style="width: 40rem;">
            <div class="card-body">
                <h5 class="card-title mb-3">{{ticket.title}}</h5>
                <p><b>Тип: </b>
                    <small>{{ticket.get_ticket_type_display}}</small></p>
                <p class="card-text">{{ticket.description}}</p>

                <div class="row">
                    <div class="col">
                        <b>Отделение: </b> {{ticket.department}}
                    </div>
                </div>

                <div class="row">
                    <div class="col">
                        <b>Дата создания: </b> {{ticket.date_created}}
                    </div>
                    <div class="col">
                        <b>Подана: </b> {{ticket.created_by.last_name}} {{ticket.created_by.first_name}}
                    </div>
                </div>

                <div class="row">
                    <div class="col">
                        <b>Статус: </b>
                        {% if ticket.ticket_status == 'Active' %}
                            <td><span class="badge bg-success">Активна</span></td>
                        {% elif ticket.ticket_status == 'Pending' %}
                            <td><span class="badge bg-warning">Ожидание</span></td>
                        {% elif ticket.ticket_status == 'Completed' %}
                            <td><span class="badge bg-danger">Закрыта</span></td>
                        {% endif %}
                    </div>
                    <div class="col">
                        <b>Кем принята: </b> {{ticket.assigned_to.last_name}} {{ticket.assigned_to.first_name}}
                    </div>
                    <div class="row">
                </div>
                </div><br>
            </div>
        </div>
    </div>
</div>

<br>
{% if not ticket.is_resolved %}
  {% if request.user.is_engineer %}
      <a href="#" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal">
          Закрыть заявку</a>
  {% endif %}
      <a href="{% url 'update-ticket' ticket.pk %}" class="btn btn-primary">Обновить заявку</a>
{% endif %}


<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Подтверждение.</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Закрыть заявку?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Отмена</button>
        <a href="{% url 'close-ticket' ticket.pk %}" class="btn btn-primary">Подтвердить</a>
      </div>
    </div>
  </div>
</div>


{% endblock content %}

templates/ticket/ticket_queue.html
{% extends 'base.html' %}

{% block content %}
<div class="card mx-auto" style="width: 76rem;">
    <div class="card-body">
        <h5 class="card-title mb-3">Очередь заявок</h5>

        <table class="table table-bordered" id="sortedTable">
            <thead>
                <th scope="col" onclick="sortTable(0)">Отделение</th>
                <th scope="col" onclick="sortTable(0)">Тип</th>
                <th scope="col" onclick="sortTable(1)">Название</th>
                <th scope="col" onclick="sortTable(2)">Дата создания</th>
                <th scope="col" onclick="sortTable(3)">Кем создана</th>
                <th scope="col">Статус</th>
                <th scope="col">Действия</th>
            </thead>
            <tbody>
            {% for ticket in tickets %}
                <tr>
                    <td><small>{{ticket.department}}</small></td>
                    <td><small>{{ticket.get_ticket_type_display}}</small></td>
                    <td><small>{{ticket.title}}</small></td>
                    <td><small>{{ticket.date_created}}</small></td>
                    <td><small>{{ticket.created_by.last_name}} {{ticket.created_by.first_name}}</small></td>
                    {% if ticket.ticket_status == 'Active' %}
                    <td><span class="badge bg-success">Активна</span></td>
                    {% elif ticket.ticket_status == 'Pending' %}
                    <td><span class="badge bg-warning">Ожидание</span></td>
                    {% elif ticket.ticket_status == 'Completed' %}
                    <td><span class="badge bg-danger">Закрыта</span></td>
                    {% endif %}
                    <td><small><a href="{% url 'accept-ticket' ticket.pk %}">Принять</a> </small></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock content %}

templates/ticket/update_ticket.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block content %}

<div class="row">
    <div class="col-md-6">
        <div class="card mx-auto" style="width: 40em;">
            <div class="card-body">
                <h5 class="card-title mb-3">Изменение заявки</h5>

                <form method="POST">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label class="form-label">Название</label>
                        {% render_field form.title class="form-control" %}
                    </div>
                    <div class="mb-3">
                        <label class="form-label">С чем проблема?</label>
                        {% render_field form.ticket_type class="form-control" %}
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Текст заявки</label>
                        {% render_field form.description class="form-control" %}
                    </div>

                    <button class="btn btn-primary">Подтвердить</button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/ticket/workspace.html
{% extends 'base.html' %}

{% block content %}
<div class="card mx-auto" style="width: 76rem;">
    <div class="card-body">
        <h5 class="card-title mb-3">Мои заявки</h5>

        <table class="table table-bordered" id="sortedTable">
            <thead>
                <th scope="col" onclick="sortTable(0)">Отделение</th>
                <th scope="col" onclick="sortTable(0)">Тип</th>
                <th scope="col" onclick="sortTable(1)">Название</th>
                <th scope="col" onclick="sortTable(2)">Дата создания</th>
                <th scope="col" onclick="sortTable(3)">Кем создана</th>
                <th scope="col">Статус</th>
                <th scope="col">Действия</th>
            </thead>
            <tbody>
            {% for ticket in tickets %}
                <tr>
                    <td><small>{{ticket.department}}</small></td>
                    <td><small>{{ticket.get_ticket_type_display}}</small></td>
                    <td><small>{{ticket.title}}</small></td>
                    <td><small>{{ticket.date_created}}</small></td>
                    <td><small>{{ticket.created_by.last_name}} {{ticket.created_by.first_name}}</small></td>
                    {% if ticket.ticket_status == 'Active' %}
                    <td><span class="badge bg-success">Активна</span></td>
                    {% elif ticket.ticket_status == 'Pending' %}
                    <td><span class="badge bg-warning">Ожидание</span></td>
                    {% elif ticket.ticket_status == 'Completed' %}
                    <td><span class="badge bg-danger">Закрыта</span></td>
                    {% endif %}
                    <td><small><a href="{% url 'ticket-details' ticket.pk %}">Детали</a> </small></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock content %}